source 'https://rubygems.org'
gem 'bloc_works', path: "../bloc_works"
gem 'bloc_record', path: '../../Bloc_Record/BlocRecord'
gem "erubis", "~> 2.7"
gem "rack", "~> 1.6"
gem 'sqlite3'
gem "rake", "~> 10.0"
